---
apiVersion: v2
name: namespaces
# version will be changed by ci
version: v1.0.4
description: Helm chart to create namespaces and ServiceAccounts
type: application
home: "https://github.com/cloud-labs-infra/helm-namespaces"
maintainers:
  - name: Mikhail Vintcukevich
    url: "https://github.com/Mishavint"
  - name: Egor Vasilyev
    url: "https://github.com/bissquit"
