{{- range $namespace := .Values.namespaces }}
{{- range $serviceaccount := $namespace.serviceaccounts }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $serviceaccount }}
  namespace: {{ $namespace.name }}
  annotations:
    kubernetes.io/service-account.name: {{ $serviceaccount }}
  labels:
    {{- include .common.labels | nindent 4 }}
type: kubernetes.io/service-account-token
{{ end }}
{{ end }}
