{{- range $namespace := .Values.namespaces }}
{{- range $serviceaccount := $namespace.serviceaccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceaccount }}
  namespace: {{ $namespace.name }}
{{ end }}
{{ end }}
