{{- range $namespace := .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace.name }}
  labels:
    name: {{ $namespace.name }}
    {{- include .common.labels | nindent 4 }}
{{- end }}
