{{- range $namespace := .Values.namespaces }}
{{- range $serviceaccount := $namespace.serviceaccounts }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-{{ $serviceaccount }}-{{ $namespace.name }}
  namespace: {{ $namespace.name }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceaccount }}
roleRef:
  kind: ClusterRole
  name: admin
{{ end }}
{{ end }}
