name: "Release"

on:
  push:
#    branches:
#      - main

jobs:
#  run-tests:
#    name: "Run tests"
#    uses: ./.github/workflows/tests.yml
#    secrets: inherit

  release:
#    needs: run-tests
    name: "Release"
    runs-on: ubuntu-20.04
    permissions: write-all
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3

      - name: Obtain release version
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        with:
          dry_run: true
          ci: false
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@4.6.3

      - name: Update chart version
        run: |
          sed 's/^version.*$/version: ${{ steps.semantic.outputs.new_release_version }}/' Chart.yaml

      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@4.6.3
