name: "Release"

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: "Run tests"
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  release:
    needs: run-tests
    name: "Release"
    runs-on: ubuntu-20.04
    permissions: write-all
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3

      - run: npm install @semantic-release/exec@6.0.3 -D

      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 21.1.1
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/exec
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@4.6.3
